apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "grpc-ldap.fullname" . }}
  labels:
    {{- include "grpc-ldap.labels" . | nindent 4 }}
spec:
  secretName: {{ include "grpc-ldap.fullname" . }}-tls
  duration: {{ .Values.secrets.tls.duration }}
  renewBefore: {{ .Values.secrets.tls.renewBefore }}
  subject: {{ .Values.secrets.tls.subject | toYaml | nindent 4 }}
  commonName: {{ include "grpc-ldap.fullname" . }}
  isCA: false
  dnsNames:
    - {{ include "grpc-ldap.fullname" . }}
  privateKey:
    rotationPolicy: Always
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  issuerRef: {{ .Values.secrets.tls.issuerRef | toYaml | nindent 4 }}
