apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "grpc-accounts.fullname" . }}-config
  labels:
    {{- include "grpc-accounts.labels" . | nindent 4 }}
data:
  config.{{ .Values.environment }}.yaml: |
    logLevel: {{ .Values.grpc.logLevel }}
    listen:
      protocol: {{ .Values.grpc.listen.protocol }}
      port: {{ .Values.grpc.listen.port }}
      tls:
        cert: {{ .Values.grpc.listen.tls.cert }}
        key: {{ .Values.grpc.listen.tls.key }}
